# Generated by Django 2.1.6 on 2019-02-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('gender', models.CharField(max_length=10)),
                ('govt_proof', models.CharField(max_length=264)),
                ('contact_num', models.BigIntegerField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=264)),
                ('room_num', models.CharField(max_length=264)),
                ('floor', models.CharField(max_length=264)),
                ('avail', models.CharField(max_length=264)),
                ('price', models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superIndex.Customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superIndex.Room'),
        ),
    ]
