# Generated by Django 2.1.6 on 2019-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superIndex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_num',
            field=models.BigIntegerField(),
        ),
    ]
