# Generated by Django 2.1.6 on 2019-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superIndex', '0004_auto_20190305_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
    ]
